fix: dimensions should be optional to embedding_openai()
timescale/pgai pull request #132
Opened 2024-10-17 16:46 UTC by jgpruitt

2024-10-17 17:36 UTC, cevian requested changes
Wait how do we know the dimensions of the vector column in the storage table then?

2024-10-17 17:37 UTC, jgpruitt commented
Crap. How did this not trip a test?

2024-10-17 17:47 UTC, jgpruitt commented
Okay I guess we have to handle this in the vectorizer code

2024-10-18 01:10 UTC, cevian approved these changes

2024-10-18 01:11 UTC, cevian commented on projects/extension/sql/ai--0.4.0.sql
>              raise warning 'one or more grant_to roles do not exist: %', _missing_roles;
I think you need to regenerate the sql before merging

2024-10-18 16:05 UTC, closed without merging