chore: add test for recursive text splitting
timescale/pgai pull request #207
Opened 2024-11-08 20:23 UTC by Askir

2024-11-11 13:55 UTC, alejandrodnm commented on projects/pgai/tests/vectorizer/conftest.py
> +        before_record_response=remove_set_cookie_header,
Does adding it to the `filter_header` list achieves the same?

2024-11-11 20:54 UTC, Askir commented on projects/pgai/tests/vectorizer/conftest.py
> +        before_record_response=remove_set_cookie_header,
yes, the filter_header only filters request headers not response header sadly.

2024-11-12 00:46 UTC, alejandrodnm approved these changes

2024-11-14 16:01 UTC, smoya commented on docs/python-integration.md
I guess this file shouldn't be here.

2024-11-14 16:20 UTC, smoya requested changes
You are adding the `docs/python-integration.md` here (empty btw). I guess you want to remove it.

2024-11-19 17:05 UTC, Askir commented on docs/python-integration.md
Yes not sure how this happened, I also thought this was already merged. My bad 😅

2024-11-19 18:21 UTC, smoya approved these changes
LGTM 🚀

2024-11-19 19:18 UTC, merged