chore: only run CI on push
timescale/pgai pull request #229
Opened 2024-11-15 16:33 UTC by JamesGuthrie

We were specifying that CI should be run on push, and on pull_request, this end up running jobs twice.

Push is the more useful of the two, because it means that you don't have to wait for a PR to be opened for the build to run against the changes.

2024-11-15 16:42 UTC, jgpruitt requested changes
There is one instance in which having the `pull_request` CI run is very helpful, and I've already run into it. If someone has already merged a new SQL file `005-bob.sql` and you are trying to add `005-fred.sql`, the `push` event won't catch the issue, but the `pull_request` event WILL catch the issue.

Thoughts?

2024-11-15 16:46 UTC, JamesGuthrie commented
I think we've been through this discussion before with Promscale. IIRC the only way to reliably make this work is to ensure that the type of situation you're talking about results in merge conflicts.

2024-11-15 17:49 UTC, jgpruitt commented
I can't think of a way to reliable cause a merge conflict for this situation. Can you?

If not, then I think we need to run CI on main on a daily schedule or something to catch these issues.

2024-11-18 17:17 UTC, Askir commented
I'd argue that the PR job is the more important one. I often push changes, that I know are broken but I want people to be able to see or reference (e.g. draft PRs), so running the on push job there is pretty redundant.

And as long as we require a branch to be up to date with main before merging this also ensures that main is never broken.

2024-11-18 17:18 UTC, Askir commented
btw if we disable the PR trigger I think PRs from forks simply don't run trough CI at all.

2024-11-19 09:18 UTC, JamesGuthrie commented
> I can't think of a way to reliable cause a merge conflict for this situation. Can you?

The only way to reliably cause merge conflicts is to serialize the migration script file names to a single file. In your example of `005-bob.sql` and `005-fred.sql`, if the "bob" change was merged first then the "conflict" file on main would contain:

```
// conflict file
001-sue.sql
002-me.sql
003-not.sql
004-dear.sql
005-bob.sql
```

While the "conflict" file in the "fred" branch would contain:
```
// conflict file
001-sue.sql
002-me.sql
003-not.sql
004-dear.sql
005-fred.sql
```

2024-11-19 09:18 UTC, JamesGuthrie commented
> I'd argue that the PR job is the more important one. I often push changes, that I know are broken but I want people to be able to see or reference (e.g. draft PRs), so running the on push job there is pretty redundant.
> 
> And as long as we require a branch to be up to date with main before merging this also ensures that main is never broken.


btw if we disable the PR trigger I think PRs from forks simply don't run trough CI at all.

2024-11-19 11:59 UTC, alejandrodnm approved these changes

2024-11-19 15:01 UTC, jgpruitt approved these changes

2024-11-19 15:01 UTC, merged